Recipe app: the final PR
Yacoubou-seidou/RoR_Group_Project pull request #19
Opened 2023-08-03 13:24 UTC by naji-97

- [ ] A login page using Devise.

- [ ] A registration page using Devise.
- [ ] A food list (with all CRUD implementation, except for 'update'), displays a list and quantity of a given food of food added by the logged-in user.
- [ ] A recipes list (with all CRUD implementation, except for 'update'),  display a list of recipes created by the logged-in user, each recipe leads to recipe details, and the user can delete the recipe if it's the owner.
- [ ] A general shopping list shows the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
it counts the total food items and total price of the missing food.
- [ ] A list of all public recipes from other users with their names and total prices Should display a list of all public recipes ordered by newest as in the wireframe.
Should lead to recipe details.

2023-08-03 18:06 UTC, OyePriscilla requested changes
Hi @naji-97 and @Yacoubou-seidou 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Set up Devise for authentication ✔️
Set up associations between models ✔️ 
Used params from browser requests in a safe way ✔️ 
Used preprocessed HTML file with embedded Ruby code ✔️ 
Used layouts and templates for shared content ✔️ 
Used database migration files to maintain database schema ✔️ 
Used validations for models ✔️ 
Secured app from n+1 problems ✔️ 
Implemented tests for the app ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 18:06 UTC, OyePriscilla commented on app/controllers/recipes_controller.rb
> +  end
- [ ] I observed that you ommitted two things as listed in the wireframe, `generate_shopping_list `and `add_ingrdient`. Kindly implemented as expected. 👍

 ## Wireframe
<img width="189" alt="Untitled" src="https://github.com/Yacoubou-seidou/RoR_Group_Project/assets/103386183/59e29159-d5ff-4fc4-9d90-b841a62370e7">

## Your design
<img width="606" alt="Untitled" src="https://github.com/Yacoubou-seidou/RoR_Group_Project/assets/103386183/0c890d82-251e-4670-b9e5-486de34cb567">

2023-08-03 18:06 UTC, OyePriscilla commented on app/controllers/foods_controller.rb
> +  end
- [ ] I was unable to delete recipe, I got the error screen shot below 👇, it indicates that there's an issue with a `has_many :through` association in your ActiveRecord models. Kindly fix it. 👍 🔴 **Please take note that I got the same error when I tried to delete a food item** 🔴

## Error from Recipe_show page
<img width="838" alt="Untitled" src="https://github.com/Yacoubou-seidou/RoR_Group_Project/assets/103386183/45331889-8b6d-404e-ac67-05ee86522716">

## Error from Food page
<img width="836" alt="Untitled" src="https://github.com/Yacoubou-seidou/RoR_Group_Project/assets/103386183/54c122bd-1362-46f7-9712-82e9257cfbd0">

2023-08-04 08:01 UTC, DeliceLydia approved these changes
## Hi Team, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


### Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-08-04 08:06 UTC, merged